spring.application.name=cuarto_modulo_api

server.port=8383

# Credenciales definidas previamente en el docker-compose
spring.datasource.url=jdbc:mysql://mysql_cuarto_modulo:3306/universidad_backend?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=desarrollador
spring.datasource.password=password_seguro_123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate para crear tablas automáticamente en base al código
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# libros.service.url=http://entorno_programacion:8080

# Tiempo máximo para conectar al servicio destino (3 segundos)
# spring.cloud.openfeign.client.config.default.connectTimeout=3000

# Tiempo máximo para leer la respuesta (5 segundos)
# spring.cloud.openfeign.client.config.default.readTimeout=5000